name: nlp-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - ipywidgets
  - plotly
  - pip
  - pip:
    - gensim
    - tensorflow
    - nltk