name: Test Notebooks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert
    
    - name: Test notebook execution
      run: |
        for notebook in NLP_*/*.ipynb; do
          echo "Testing $notebook"
          jupyter nbconvert --to notebook --execute "$notebook" --output /tmp/test_output.ipynb
        done